[workspace]
resolver = "2"
members = [
    "crates/backend",
    "crates/frontend/src/ui",
    "crates/frontend/src/web",
    "crates/frontend/src/desktop",
    "crates/frontend/src/mobile",
    "crates/frontend/src/api",
]


[workspace.dependencies]
dioxus = { version = "0.6.0" }

ui = { path = "crates/frontend/src/ui" }
api = { path = "crates/frontend/src/api" }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
