[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bench]]
name = "bench_backend"
harness = false

[dev-dependencies]
criterion = { version = "0.7.0", features = [
  "cargo_bench_support",
  "real_blackbox",
     "html_reports"
] }




[features]
default = []
mimalloc = ["dep:mimalloc"]
mimalloc-secure = ["dep:mimalloc", "mimalloc/secure"]
mimalloc-v3=["dep:mimalloc","mimalloc/v3"]
mimalloc-v3-secure=["dep:mimalloc","mimalloc/v3","mimalloc/secure"]
jemallocator = ["dep:jemallocator"]
scudo=["dep:scudo"]
snmalloc=["dep:snmalloc-rs","snmalloc-rs/native-cpu"]
snmalloc-secure=["dep:snmalloc-rs","snmalloc-rs/native-cpu","snmalloc-rs/check"]
tcmalloc=["dep:tcmalloc"]
rpmalloc=["dep:rpmalloc"]

[dependencies]
anyhow = "1.0.99"
base32 = "0.5"
bitflags = { version = "2.6.0", features = ["serde"] }
blake3 = "1.6"
chrono = { version = "0.4", features = ["serde"] }
ed25519-dalek = { version = "2.2.0", features = ["rand_core", "pkcs8"]}
hex = "0.4.3"
keyring = { version = "3", features = ["sync-secret-service", "apple-native", "windows-native"] }
mimalloc = { version = "0.1.48", optional = true }  #
jemallocator = { version = "0.5.4", optional = true }
quinn = "0.11.8"
rand = "0.8.0"
rcgen = { version = "0.14.3", default-features = false, features = ["x509-parser", "ring"] }
rustls = { version = "0.23.31", default-features = false, features = ["ring", "std"] }
serde = { version = "1.0.219", features = ["derive"] }
serial_test = "3.2.0"
sha2 = "0.10.9"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["macros", "rt", "time"] }
x509-parser = "0.18.0"
zeroize = { version = "1.8.1", features = ["serde"] }
scudo = { version = "0.1.3", optional = true }
snmalloc-rs ={ version = "0.3.8", optional = true }
tcmalloc = { version = "0.3.0",optional=true, features = ["bundled"] } # needs to be bundled incase lacking the .so file on your system
rpmalloc = {version="0.2.2",optional=true}

[package.metadata.cargo-allocation]
exclusive = true
